### PR TITLE
add file elisp-depend/.nosearch

### PR DESCRIPTION
**Pull request by tarsius**
This prevents `normal-top-level-add-subdirs-to-load-path`
from adding "elisp-depend/" to the `load-path`.

### CODE REVIEW

**Comment by tarsius** [comment]
ping

**Comment by tehom** [comment]
> ping

Am still here, but haven't worked on elisp for some time now.

```
Tom Breton (Tehom)
```

**Comment by tarsius** [comment]
Alright :)

**Comment by Wilfred** [comment]
@tehom would you be open to giving a few extra users commit rights, so they can contribute to this package?

**Comment by tarsius** [comment]
I have forked this to https://github.com/emacsorphanage/elisp-depend and updated the Melpa recipe accordingly.

@Wilfred I can give you commit access. Do you have a patch for #2?

**Comment by Wilfred** [comment]
@tarsius I don't, but I could write a patch for #2 in a few days if you're interested.

**Comment by tarsius** [comment]
I don't really use this, so it is up to you.

I use functions from my [`packed`](https://github.com/tarsius/packed) package instead. Depending on your use-case you might want to do the same. I use it to determine the features provided and required by the [6354 packages in the Emacsmirror's database](https://emacsmirror.net/stats/compare.html), so I would say it has been battle proofed. However it uses regex search to find require and provide forms and does not load the libraries it inspects and that might be an advantage or a disadvantage depending on what you expect.

**Pull request closed without merging**
